import { type GlobalCommandDescriptor } from '@habitat/shared';

const COMMANDS: GlobalCommandDescriptor[] = [
  {
    id: 'new-session',
    command: '/new',
    label: 'New Session',
    group: 'session',
    sourceLabel: 'GitHub',
    description: 'Start a fresh session when context has drifted too far.',
    enabled: false,
    requiresOptIn: false,
    dangerLevel: 'safe',
  },
  {
    id: 'reset-session',
    command: '/reset',
    label: 'Reset Overrides',
    group: 'session',
    sourceLabel: 'OpenClaw',
    description: 'Clear session-level overrides back to configured defaults.',
    enabled: false,
    requiresOptIn: false,
    dangerLevel: 'privileged',
  },
  {
    id: 'compact-session',
    command: '/compact',
    label: 'Compact History',
    group: 'session',
    sourceLabel: 'Openclawlaunch',
    description: 'Summarize and compress history before long management tasks.',
    enabled: false,
    requiresOptIn: false,
    dangerLevel: 'safe',
  },
  {
    id: 'model-switch',
    command: '/model',
    label: 'Switch Model',
    group: 'model',
    sourceLabel: 'GitHub',
    description: 'Queue or apply a model switch for the current session.',
    enabled: false,
    requiresOptIn: false,
    dangerLevel: 'privileged',
    argsHint: '[ref]',
  },
  {
    id: 'model-status',
    command: '/model status',
    label: 'Model Status',
    group: 'model',
    sourceLabel: 'OpenClaw',
    description: 'Show active model, provider endpoint, auth mode, and key status.',
    enabled: true,
    requiresOptIn: false,
    dangerLevel: 'safe',
  },
  {
    id: 'fast-mode',
    command: '/fast',
    label: 'Priority Tier',
    group: 'model',
    sourceLabel: 'OpenClaw',
    description: 'Toggle supported provider priority service tier.',
    enabled: false,
    requiresOptIn: false,
    dangerLevel: 'privileged',
    argsHint: 'on|off',
  },
  {
    id: 'status',
    command: '/status',
    label: 'Gateway Status',
    group: 'visibility',
    sourceLabel: 'GitHub',
    description: 'Show gateway health, active model, session info, and quota state.',
    enabled: true,
    requiresOptIn: false,
    dangerLevel: 'safe',
  },
  {
    id: 'usage',
    command: '/usage',
    label: 'Usage Detail',
    group: 'visibility',
    sourceLabel: 'OpenClaw',
    description: 'Control token and cost metadata shown with replies.',
    enabled: false,
    requiresOptIn: false,
    dangerLevel: 'safe',
    argsHint: 'off|tokens|full',
  },
  {
    id: 'verbose',
    command: '/verbose',
    label: 'Verbose Debug',
    group: 'visibility',
    sourceLabel: 'OpenClaw',
    description: 'Temporarily reveal deeper tool and runtime output while debugging.',
    enabled: false,
    requiresOptIn: false,
    dangerLevel: 'privileged',
    argsHint: 'on|off',
  },
  {
    id: 'trace',
    command: '/trace',
    label: 'Plugin Trace',
    group: 'visibility',
    sourceLabel: 'OpenClaw',
    description: 'Reveal plugin-owned trace lines without full tool chatter.',
    enabled: false,
    requiresOptIn: false,
    dangerLevel: 'safe',
    argsHint: 'on|off',
  },
  {
    id: 'config',
    command: '/config',
    label: 'Config File',
    group: 'power_user',
    sourceLabel: 'Openclawcn',
    description: 'Read or write openclaw.json when commands.config is enabled.',
    enabled: false,
    requiresOptIn: true,
    dangerLevel: 'dangerous',
    argsHint: 'show|get|set|unset',
  },
  {
    id: 'debug',
    command: '/debug',
    label: 'Runtime Debug',
    group: 'power_user',
    sourceLabel: 'Openclawcn',
    description: 'Apply runtime-only config changes that vanish on restart.',
    enabled: false,
    requiresOptIn: true,
    dangerLevel: 'dangerous',
    argsHint: 'show|set|unset|reset',
  },
  {
    id: 'bash',
    command: '/bash',
    label: 'Host Shell',
    group: 'power_user',
    sourceLabel: 'GitHub',
    description: 'Run a shell command inside the OpenClaw container when explicitly allowed.',
    enabled: false,
    requiresOptIn: true,
    dangerLevel: 'dangerous',
    argsHint: '<command>',
  },
  {
    id: 'think',
    command: '/think',
    label: 'Thinking Depth',
    group: 'thinking',
    sourceLabel: 'GitHub',
    description: 'Set reasoning depth for complex Unraid/OpenClaw decisions.',
    enabled: false,
    requiresOptIn: false,
    dangerLevel: 'safe',
    argsHint: '<level>',
  },
];

export class OpenClawCommandService {
  listDescriptors(): GlobalCommandDescriptor[] {
    return COMMANDS.map(command => ({ ...command }));
  }

  preview(id: string): { command: GlobalCommandDescriptor; executable: false; message: string } {
    const command = COMMANDS.find(candidate => candidate.id === id);
    if (!command) {
      throw new Error(`Unknown command: ${id}`);
    }
    return {
      command: { ...command },
      executable: false,
      message: command.enabled
        ? 'This command is exposed as a UI shell descriptor; execution wiring is intentionally deferred.'
        : 'This command is visible for planning but is not executable until the matching OpenClaw permission is enabled.',
    };
  }
}
